from django.urls import path
from . import views

urlpatterns = [
    path("", views.home, name="home"),
    # path("dashboard/", views.dashboard, name="dashboard"),
    path("dashboard/", views.Dashboard.as_view(), name="dashboard"),
    # path("admin-dashboard/", views.admin_panel, name="admin_panel"),
    path("admin-dashboard/", views.AdminPanel.as_view(), name="admin_panel"),
    # path("users/", views.all_users, name="all_users"),
    # path("create_event/", views.create_event, name="create_event"),
    path("create_event/", views.CreateEvent.as_view(), name="create_event"),
    # path("create_category/", views.create_category, name="create_category"),
    path("create_category/", views.CreateCategory.as_view(), name="create_category"),
    # path("update_event/<int:event_id>/", views.update_event, name="update_event"),
    path("update_event/<int:event_id>/", views.UpdateEvent.as_view(), name="update_event"),
    # path("update_category/<int:category_id>/", views.update_category, name="update_category"),
    path("update_category/<int:category_id>/", views.UpdateCategory.as_view(), name="update_category"),
    # path("event_list/", views.read_events, name="event_list"),
    path("event_list/", views.ReadEvents.as_view(), name="event_list"),
    # path("category_list/", views.read_categories, name="category_list"),
    path("category_list/", views.ReadCategories.as_view(), name="category_list"),
    # path("event/<int:event_id>/", views.event_detail, name="event_detail"),
    path("event/<int:event_id>/", views.EventDetail.as_view(), name="event_detail"),
    # path("category/<int:category_id>/events/", views.categorycal_events, name="categorycal_events"),    
    path("category/<int:category_id>/events/", views.CategoryEvents.as_view(), name="categorycal_events"),    
    path("delete_event/<int:event_id>/", views.DeleteEvent.as_view(), name="delete_event"),
    # path("participant/<int:participant_id>/events/", views.participantcal_events, name="participantcal_events"),
    path("participant/<int:participant_id>/events/", views.ParticipantEvents.as_view(), name="participantcal_events"),
    # path("delete_category/<int:category_id>/", views.delete_category, name="delete_category"),
    path("delete_category/<int:category_id>/", views.DeleteCategory.as_view(), name="delete_category"),
    # path("participants/", views.all_users, name="all_participants"),
    path("participants/", views.AllUsers.as_view(), name="all_participants"),
    # path("organizers/", views.all_organizers, name="all_organizers"),
    path("organizers/", views.AllOrganizers.as_view(), name="all_organizers"),
    # path("create_group/", views.create_group, name="create_group"),
    path("create_group/", views.CreateGroup.as_view(), name="create_group"),
    # path("assign_group/<int:user_id>/", views.assign_user_group, name="assign_user_group"),
    path("assign_group/<int:user_id>/", views.AssignUserGroup.as_view(), name="assign_user_group"),
    # path("all_roles/", views.all_roles_with_permissions, name="all_user_roles"),
    path("all_roles/", views.AllRolesWithPermissions.as_view(), name="all_user_roles"),
    # path("rvsp/<int:event_id>/", views.rvsp_events, name="rsvp_event"),
    path("rvsp/<int:event_id>/", views.RSVPEvents.as_view(), name="rsvp_event"),
    # path('event/<int:event_id>/rsvp/', views.rvsp_events, name='rsvp_events'),
    # path('event/<int:event_id>/rsvp/', views.RSVPEvents.as_view(), name='rsvp_events'),
    path("participant/<int:participant_id>/events/", views.ParticipantEvents.as_view(), name="participant_events"),
]